import {
  // Tuin & buitenruimte
  Apple,
  Barrel,
  Bird,
  Birdhouse,
  Carrot,
  Cherry,
  CloudRain,
  Clover,
  Compass,
  Droplet,
  Droplets,
  Fence,
  Fish,
  Flag,
  Flower,
  Flower2,
  Grape,
  Lamp,
  Leaf,
  LeafyGreen,
  Lightbulb,
  Logs,
  MapPin,
  Milestone,
  Mountain,
  MountainSnow,
  Palmtree,
  Rabbit,
  RockingChair,
  Shovel,
  Shrub,
  Signpost,
  Snail,
  Snowflake,
  Spade,
  Sprout,
  Squirrel,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  TentTree,
  TreeDeciduous,
  TreePine,
  Trees,
  Umbrella,
  Waves,
  Wheat,
  Wind,
  Worm,
  // Bouw & constructie
  Anvil,
  AppWindow,
  Axe,
  Blocks,
  Bolt,
  BrickWall,
  Building,
  Building2,
  Cone,
  Construction,
  DoorClosed,
  DoorOpen,
  Drill,
  Factory,
  Frame,
  Grid3x3,
  Hammer,
  HardHat,
  House,
  Key,
  Layers,
  Layers2,
  Lock,
  Nut,
  PencilRuler,
  Pickaxe,
  Ruler,
  RulerDimensionLine,
  Shield,
  Square,
  SquareDashed,
  Stone,
  ToolCase,
  Toolbox,
  ToyBrick,
  TrafficCone,
  Unlock,
  Warehouse,
  Wrench,
  // Sanitair & installatie
  AirVent,
  Bath,
  Battery,
  BatteryCharging,
  Cable,
  CircuitBoard,
  Cog,
  Fan,
  Filter,
  Flame,
  FlameKindling,
  Gauge,
  GaugeCircle,
  GlassWater,
  Plug,
  PlugZap,
  Power,
  Router,
  ShowerHead,
  SoapDispenserDroplet,
  SolarPanel,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Toilet,
  WashingMachine,
  Wifi,
  Zap,
  // Keuken & interieur
  Archive,
  Armchair,
  Bed,
  BedDouble,
  Blender,
  Blinds,
  ChefHat,
  Coffee,
  Cookie,
  CookingPot,
  CupSoda,
  LampCeiling,
  LampDesk,
  LampFloor,
  Microwave,
  MirrorRectangular,
  Refrigerator,
  Sofa,
  Table,
  Table2,
  Utensils,
  UtensilsCrossed,
  // Afwerking
  Brush,
  BrushCleaning,
  Grid2x2,
  LayoutGrid,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  Paintbrush2,
  Palette,
  RollerCoaster,
  Scissors,
  SprayCan,
  SquareStack,
  SwatchBook,
  Wallpaper,
  // Algemeen & bedrijfsvoering
  AlarmClock,
  Award,
  BadgeCheck,
  BadgePercent,
  Banknote,
  Bell,
  Box,
  Boxes,
  Briefcase,
  BriefcaseBusiness,
  Calculator,
  Calendar,
  Car,
  Caravan,
  CheckCircle,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coins,
  Contact,
  Container,
  CreditCard,
  Euro,
  FileText,
  Folder,
  Forklift,
  Gem,
  Gift,
  HandHelping,
  Handshake,
  HeartHandshake,
  Inbox,
  Mail,
  Map,
  Medal,
  Megaphone,
  Navigation2,
  Package,
  Package2,
  PackageCheck,
  Percent,
  Phone,
  PiggyBank,
  Receipt,
  ReceiptEuro,
  Recycle,
  Route,
  Scale,
  ShieldCheck,
  Signature,
  Sparkles,
  Stamp,
  Star,
  Target,
  ThumbsUp,
  Timer,
  Trash2,
  Trophy,
  Truck,
  TruckElectric,
  Users,
  Van,
  Verified,
  Wallet,
  type LucideIcon,
} from "lucide-react";

// Curated, vakman-relevant subset van lucide-react-icons waaruit de vakman
// kan kiezen voor een product. Keys zijn de lucide-componentnamen en worden
// as-is opgeslagen in de database (Product.icoon) — dus nooit een bestaande
// key hernoemen of verwijderen, dat "unset" stilzwijgend het icoon van elke
// vakman die 'm al gekozen had. Nieuwe icons toevoegen kan altijd veilig.
//
// PRODUCT_ICON_CATEGORIES groepeert dezelfde set voor de icon-picker (zoeken
// + categorie-filters, zie app/components/ui/icon-picker.tsx) — een icon
// die in meerdere categorieën zou passen staat hier maar op één plek, maar
// blijft via zoeken op naam altijd vindbaar ongeacht categorie.
export const PRODUCT_ICON_CATEGORIES: { label: string; icons: string[] }[] = [
  {
    label: "Tuin & buitenruimte",
    icons: ["Apple", "Barrel", "Bird", "Birdhouse", "Carrot", "Cherry", "CloudRain", "Clover", "Compass", "Droplet", "Droplets", "Fence", "Fish", "Flag", "Flower", "Flower2", "Grape", "Lamp", "Leaf", "LeafyGreen", "Lightbulb", "Logs", "MapPin", "Milestone", "Mountain", "MountainSnow", "Palmtree", "Rabbit", "RockingChair", "Shovel", "Shrub", "Signpost", "Snail", "Snowflake", "Spade", "Sprout", "Squirrel", "Sun", "SunDim", "SunMedium", "SunMoon", "TentTree", "TreeDeciduous", "TreePine", "Trees", "Umbrella", "Waves", "Wheat", "Wind", "Worm"],
  },
  {
    label: "Bouw & constructie",
    icons: ["Anvil", "AppWindow", "Axe", "Blocks", "Bolt", "BrickWall", "Building", "Building2", "Cone", "Construction", "DoorClosed", "DoorOpen", "Drill", "Factory", "Frame", "Grid3x3", "Hammer", "HardHat", "House", "Key", "Layers", "Layers2", "Lock", "Nut", "PencilRuler", "Pickaxe", "Ruler", "RulerDimensionLine", "Shield", "Square", "SquareDashed", "Stone", "ToolCase", "Toolbox", "ToyBrick", "TrafficCone", "Unlock", "Warehouse", "Wrench"],
  },
  {
    label: "Sanitair & installatie",
    icons: ["AirVent", "Bath", "Battery", "BatteryCharging", "Cable", "CircuitBoard", "Cog", "Fan", "Filter", "Flame", "FlameKindling", "Gauge", "GaugeCircle", "GlassWater", "Plug", "PlugZap", "Power", "Router", "ShowerHead", "SoapDispenserDroplet", "SolarPanel", "Thermometer", "ThermometerSnowflake", "ThermometerSun", "Toilet", "WashingMachine", "Wifi", "Zap"],
  },
  {
    label: "Keuken & interieur",
    icons: ["Archive", "Armchair", "Bed", "BedDouble", "Blender", "Blinds", "ChefHat", "Coffee", "Cookie", "CookingPot", "CupSoda", "LampCeiling", "LampDesk", "LampFloor", "Microwave", "MirrorRectangular", "Refrigerator", "Sofa", "Table", "Table2", "Utensils", "UtensilsCrossed"],
  },
  {
    label: "Afwerking",
    icons: ["Brush", "BrushCleaning", "Grid2x2", "LayoutGrid", "PaintBucket", "PaintRoller", "Paintbrush", "Paintbrush2", "Palette", "RollerCoaster", "Scissors", "SprayCan", "SquareStack", "SwatchBook", "Wallpaper"],
  },
  {
    label: "Algemeen & bedrijfsvoering",
    icons: ["AlarmClock", "Award", "BadgeCheck", "BadgePercent", "Banknote", "Bell", "Box", "Boxes", "Briefcase", "BriefcaseBusiness", "Calculator", "Calendar", "Car", "Caravan", "CheckCircle", "Clipboard", "ClipboardCheck", "ClipboardList", "Clock", "Coins", "Contact", "Container", "CreditCard", "Euro", "FileText", "Folder", "Forklift", "Gem", "Gift", "HandHelping", "Handshake", "HeartHandshake", "Inbox", "Mail", "Map", "Medal", "Megaphone", "Navigation2", "Package", "Package2", "PackageCheck", "Percent", "Phone", "PiggyBank", "Receipt", "ReceiptEuro", "Recycle", "Route", "Scale", "ShieldCheck", "Signature", "Sparkles", "Stamp", "Star", "Target", "ThumbsUp", "Timer", "Trash2", "Trophy", "Truck", "TruckElectric", "Users", "Van", "Verified", "Wallet"],
  },
];

// Nederlandse zoektermen per icon, voor de zoekbalk in de picker — een
// vakman zoekt op een herkenbaar woord ("schutting", "douche") in plaats
// van de Engelse lucide-naam ("Fence", "ShowerHead") te hoeven kennen.
export const PRODUCT_ICON_KEYWORDS: Record<string, string> = {
  AirVent: "ventilatie luchtafvoer mechanische ventilatie",
  AlarmClock: "wekker herinnering planning",
  Anvil: "aambeeld smid metaalbewerking",
  AppWindow: "raam venster kozijn",
  Apple: "appel fruit fruitboom",
  Archive: "opbergkast kast opslag",
  Armchair: "fauteuil stoel meubilair",
  Award: "prijs kwaliteit keurmerk",
  Axe: "bijl hakken gereedschap",
  BadgeCheck: "gecertificeerd keurmerk garantie",
  BadgePercent: "korting actie aanbieding",
  Banknote: "geld betaling contant",
  Barrel: "vat regenton ton",
  Bath: "bad badkamer",
  Battery: "accu batterij opslag",
  BatteryCharging: "laden accu opladen",
  Bed: "bed slaapkamer",
  BedDouble: "tweepersoonsbed slaapkamer",
  Bell: "melding herinnering notificatie",
  Bird: "vogel",
  Birdhouse: "vogelhuisje nestkast",
  Blender: "blender keukenapparatuur",
  Blinds: "jaloezie raamdecoratie",
  Blocks: "blokken bouwstenen fundering",
  Bolt: "bout bevestiging",
  Box: "doos verpakking materiaal",
  Boxes: "dozen voorraad materiaal",
  BrickWall: "muur gevel metselwerk baksteen steen",
  Briefcase: "zakelijk bedrijf koffer",
  BriefcaseBusiness: "zakelijk bedrijfsvoering",
  Brush: "kwast schilderen verf",
  BrushCleaning: "reinigen schoonmaken",
  Building: "gebouw pand",
  Building2: "gebouw kantoor pand",
  Cable: "kabel bekabeling elektra",
  Calculator: "rekenmachine prijsberekening offerte",
  Calendar: "agenda planning afspraak",
  Car: "auto voertuig vervoer",
  Caravan: "caravan aanhanger vervoer",
  Carrot: "wortel groente moestuin",
  CheckCircle: "afgerond goedgekeurd klaar",
  ChefHat: "koken keuken",
  Cherry: "kers fruit",
  CircuitBoard: "elektra bedrading installatie groepenkast",
  Clipboard: "checklist klembord inspectie",
  ClipboardCheck: "keuring controle checklist",
  ClipboardList: "takenlijst checklist werkbon",
  Clock: "tijd arbeidstijd uren",
  CloudRain: "regen bui neerslag weer",
  Clover: "klaver gazon gras",
  Coffee: "koffie keuken",
  Cog: "instelling mechaniek techniek",
  Coins: "geld kosten prijs",
  Compass: "kompas richting oriëntatie",
  Cone: "pion afzetting bouwplaats",
  Construction: "bouwplaats bouw verbouwing",
  Contact: "contactpersoon klant",
  Container: "container opslag afvalcontainer",
  Cookie: "bakken keuken",
  CookingPot: "pan koken keuken",
  CreditCard: "betaling factuur",
  CupSoda: "beker keuken",
  DoorClosed: "deur dicht",
  DoorOpen: "deur open",
  Drill: "boormachine boren gereedschap",
  Droplet: "druppel water irrigatie besproeiing",
  Droplets: "water regen irrigatie besproeiing",
  Euro: "geld prijs kosten",
  Factory: "fabriek bedrijfspand",
  Fan: "ventilator afzuiging",
  Fence: "schutting hek omheining erfafscheiding",
  FileText: "document offerte contract",
  Filter: "filter waterfilter luchtfilter",
  Fish: "vis vijver",
  Flag: "vlag markering",
  Flame: "gas verwarming cv",
  FlameKindling: "haard open haard vuur",
  Flower: "bloem beplanting border perk",
  Flower2: "bloem beplanting border perk",
  Folder: "map dossier archief",
  Forklift: "vorkheftruck transport magazijn",
  Frame: "kozijn lijst raamwerk",
  Gauge: "meter drukmeter gasmeter",
  GaugeCircle: "meter thermostaat",
  Gem: "kwaliteit premium waardevol",
  Gift: "cadeau bonus actie",
  GlassWater: "water drinkwater kraan",
  Grape: "druif wijngaard",
  Grid2x2: "tegels tegelwerk tegelpatroon",
  Grid3x3: "raster tegels indeling",
  Hammer: "hamer gereedschap",
  HandHelping: "service hulp dienstverlening",
  Handshake: "deal akkoord overeenkomst",
  HardHat: "veiligheidshelm bouwvakker veiligheid helm",
  HeartHandshake: "klanttevredenheid service",
  House: "huis woning",
  Inbox: "aanvragen berichten postvak",
  Key: "sleutel toegang slot",
  Lamp: "tuinverlichting lamp buitenverlichting",
  LampCeiling: "plafondlamp verlichting",
  LampDesk: "bureaulamp verlichting",
  LampFloor: "vloerlamp verlichting",
  Layers: "lagen isolatie opbouw",
  Layers2: "lagen isolatie",
  LayoutGrid: "tegels vloerpatroon",
  Leaf: "blad plant beplanting",
  LeafyGreen: "plant groen blad beplanting",
  Lightbulb: "lamp verlichting tuinverlichting",
  Lock: "slot veiligheid",
  Logs: "hout brandhout boomstam",
  Mail: "e-mail post contact",
  Map: "gebied werkgebied locatie",
  MapPin: "locatie adres plek",
  Medal: "kwaliteit prestatie keurmerk",
  Megaphone: "aankondiging marketing promotie",
  Microwave: "magnetron keukenapparatuur",
  Milestone: "mijlpaal markering paal",
  MirrorRectangular: "spiegel badkamer interieur",
  Mountain: "berg landschap",
  MountainSnow: "berg sneeuw",
  Navigation2: "route navigatie aanrijden",
  Nut: "moer bevestiging",
  Package: "pakket materiaal levering",
  Package2: "pakket verzending",
  PackageCheck: "levering geleverd",
  PaintBucket: "verf verfblik schilderwerk",
  PaintRoller: "verfroller schilderwerk",
  Paintbrush: "kwast schilderen",
  Paintbrush2: "kwast verticaal schilderen",
  Palette: "kleuren verfkleuren kleurenpalet",
  Palmtree: "palmboom boom tropisch",
  PencilRuler: "tekenen meten ontwerp",
  Percent: "korting percentage btw",
  Phone: "telefoon bellen contact",
  Pickaxe: "houweel breekijzer slopen",
  PiggyBank: "sparen budget besparing",
  Plug: "stopcontact stekker elektra",
  PlugZap: "laadpunt elektra oplaadpaal",
  Power: "stroom elektra aan-uit",
  Rabbit: "konijn dier tuindier",
  Receipt: "bon factuur kassabon",
  ReceiptEuro: "factuur kosten",
  Recycle: "recycling afvoer hergebruik",
  Refrigerator: "koelkast keukenapparatuur",
  RockingChair: "schommelstoel tuinmeubel terras",
  RollerCoaster: "vloerafwerking plint",
  Route: "route rit planning",
  Router: "wifi internet domotica",
  Ruler: "meetlat meten afmeting",
  RulerDimensionLine: "meten afmeting maatvoering",
  Scale: "weegschaal gewicht balans",
  Scissors: "schaar behang knippen",
  Shield: "bescherming garantie veiligheid",
  ShieldCheck: "garantie verzekering veiligheid",
  Shovel: "schep spade graven",
  ShowerHead: "douche doucheput",
  Shrub: "struik heester beplanting",
  Signature: "handtekening akkoord ondertekenen",
  Signpost: "wegwijzer bordje",
  Snail: "slak tuindier",
  Snowflake: "sneeuw winter",
  SoapDispenserDroplet: "zeeppompje badkamer",
  Sofa: "bank meubilair woonkamer",
  SolarPanel: "zonnepaneel zonne-energie",
  Spade: "spade schep graven tuingereedschap",
  Sparkles: "schoonmaak oplevering nieuw",
  SprayCan: "spuiten spuitverf sauswerk",
  Sprout: "kiem zaailing planten",
  Square: "vierkant raam kozijn",
  SquareDashed: "bouwtekening plattegrond blueprint",
  SquareStack: "vloerlagen stapelen plaatmateriaal",
  Squirrel: "eekhoorn tuindier",
  Stamp: "stempel goedkeuring officieel",
  Star: "beoordeling kwaliteit favoriet",
  Stone: "steen natuursteen",
  Sun: "zon terras",
  SunDim: "zon schemer",
  SunMedium: "zon",
  SunMoon: "dag nacht zon",
  SwatchBook: "kleurstaal materiaalstaal behang",
  Table: "tafel werkblad meubilair",
  Table2: "keukeneiland werkblad",
  Target: "doel planning",
  TentTree: "boom tent kamperen",
  Thermometer: "temperatuur thermostaat",
  ThermometerSnowflake: "airco koeling",
  ThermometerSun: "verwarming warmtepomp",
  ThumbsUp: "goedkeuring tevredenheid",
  Timer: "tijd planning uren",
  Toilet: "toilet wc badkamer",
  ToolCase: "gereedschapskist gereedschap",
  Toolbox: "gereedschapskist gereedschap",
  ToyBrick: "bouwsteen fundering",
  TrafficCone: "afzetting pion bouwplaats",
  Trash2: "afval sloop opruimen",
  TreeDeciduous: "boom loofboom",
  TreePine: "boom naaldboom conifeer",
  Trees: "bomen bos",
  Trophy: "prestatie kwaliteit winnaar",
  Truck: "vrachtwagen transport levering",
  TruckElectric: "elektrische bus duurzaam vervoer",
  Umbrella: "parasol terras schaduw",
  Unlock: "open toegang",
  Users: "team medewerkers klanten",
  Utensils: "keukengerei bestek",
  UtensilsCrossed: "keuken koken",
  Van: "bestelbus vervoer transport",
  Verified: "geverifieerd gecontroleerd betrouwbaar",
  Wallet: "portemonnee budget kosten",
  Wallpaper: "behang wandafwerking",
  Warehouse: "loods opslag magazijn",
  WashingMachine: "wasmachine apparatuur",
  Waves: "water vijver zwembad",
  Wheat: "graan gewas landbouw",
  Wifi: "wifi internet domotica",
  Wind: "wind ventilatie",
  Worm: "compost grond tuin",
  Wrench: "moersleutel gereedschap",
  Zap: "elektra stroom energie",
};

export const PRODUCT_ICONS: Record<string, LucideIcon> = {
  AirVent,
  AlarmClock,
  Anvil,
  AppWindow,
  Apple,
  Archive,
  Armchair,
  Award,
  Axe,
  BadgeCheck,
  BadgePercent,
  Banknote,
  Barrel,
  Bath,
  Battery,
  BatteryCharging,
  Bed,
  BedDouble,
  Bell,
  Bird,
  Birdhouse,
  Blender,
  Blinds,
  Blocks,
  Bolt,
  Box,
  Boxes,
  BrickWall,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  BrushCleaning,
  Building,
  Building2,
  Cable,
  Calculator,
  Calendar,
  Car,
  Caravan,
  Carrot,
  CheckCircle,
  ChefHat,
  Cherry,
  CircuitBoard,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudRain,
  Clover,
  Coffee,
  Cog,
  Coins,
  Compass,
  Cone,
  Construction,
  Contact,
  Container,
  Cookie,
  CookingPot,
  CreditCard,
  CupSoda,
  DoorClosed,
  DoorOpen,
  Drill,
  Droplet,
  Droplets,
  Euro,
  Factory,
  Fan,
  Fence,
  FileText,
  Filter,
  Fish,
  Flag,
  Flame,
  FlameKindling,
  Flower,
  Flower2,
  Folder,
  Forklift,
  Frame,
  Gauge,
  GaugeCircle,
  Gem,
  Gift,
  GlassWater,
  Grape,
  Grid2x2,
  Grid3x3,
  Hammer,
  HandHelping,
  Handshake,
  HardHat,
  HeartHandshake,
  House,
  Inbox,
  Key,
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  Layers,
  Layers2,
  LayoutGrid,
  Leaf,
  LeafyGreen,
  Lightbulb,
  Lock,
  Logs,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  Microwave,
  Milestone,
  MirrorRectangular,
  Mountain,
  MountainSnow,
  Navigation2,
  Nut,
  Package,
  Package2,
  PackageCheck,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  Paintbrush2,
  Palette,
  Palmtree,
  PencilRuler,
  Percent,
  Phone,
  Pickaxe,
  PiggyBank,
  Plug,
  PlugZap,
  Power,
  Rabbit,
  Receipt,
  ReceiptEuro,
  Recycle,
  Refrigerator,
  RockingChair,
  RollerCoaster,
  Route,
  Router,
  Ruler,
  RulerDimensionLine,
  Scale,
  Scissors,
  Shield,
  ShieldCheck,
  Shovel,
  ShowerHead,
  Shrub,
  Signature,
  Signpost,
  Snail,
  Snowflake,
  SoapDispenserDroplet,
  Sofa,
  SolarPanel,
  Spade,
  Sparkles,
  SprayCan,
  Sprout,
  Square,
  SquareDashed,
  SquareStack,
  Squirrel,
  Stamp,
  Star,
  Stone,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  SwatchBook,
  Table,
  Table2,
  Target,
  TentTree,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  ThumbsUp,
  Timer,
  Toilet,
  ToolCase,
  Toolbox,
  ToyBrick,
  TrafficCone,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  Trophy,
  Truck,
  TruckElectric,
  Umbrella,
  Unlock,
  Users,
  Utensils,
  UtensilsCrossed,
  Van,
  Verified,
  Wallet,
  Wallpaper,
  Warehouse,
  WashingMachine,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Worm,
  Wrench,
  Zap,
};

export const PRODUCT_ICON_NAMES = Object.keys(PRODUCT_ICONS);

export function getProductIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return PRODUCT_ICONS[name] ?? null;
}
