import {
  TreePine,
  TreeDeciduous,
  Trees,
  Palmtree,
  Leaf,
  LeafyGreen,
  Sprout,
  Flower,
  Flower2,
  Shrub,
  Fence,
  Shovel,
  Axe,
  Pickaxe,
  Hammer,
  Wrench,
  Scissors,
  PaintRoller,
  PaintBucket,
  Droplet,
  Droplets,
  Waves,
  Sun,
  Wind,
  Truck,
  Package,
  Ruler,
  BrickWall,
  Stone,
  ToyBrick,
  House,
  Warehouse,
  Recycle,
  Trash2,
  Lightbulb,
  Lamp,
  type LucideIcon,
} from "lucide-react";

// Curated, hovenier-relevant subset of lucide-react icons the hovenier can
// pick from for a dienst or product. Keys are stored as-is in the database
// (Service.icoon / Product.icoon), so don't rename existing keys — that
// would silently "unset" the icon for anyone who already picked it.
export const PRODUCT_ICONS: Record<string, LucideIcon> = {
  TreePine,
  TreeDeciduous,
  Trees,
  Palmtree,
  Leaf,
  LeafyGreen,
  Sprout,
  Flower,
  Flower2,
  Shrub,
  Fence,
  Shovel,
  Axe,
  Pickaxe,
  Hammer,
  Wrench,
  Scissors,
  PaintRoller,
  PaintBucket,
  Droplet,
  Droplets,
  Waves,
  Sun,
  Wind,
  Truck,
  Package,
  Ruler,
  BrickWall,
  Stone,
  ToyBrick,
  House,
  Warehouse,
  Recycle,
  Trash2,
  Lightbulb,
  Lamp,
};

export const PRODUCT_ICON_NAMES = Object.keys(PRODUCT_ICONS);

export function getProductIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return PRODUCT_ICONS[name] ?? null;
}
